# Generated by Django 5.0.6 on 2026-07-25 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_country_user_pronouns_user_skin_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
