# Generated by Django 5.0.6 on 2026-07-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_word_unlock_requirement'),
        ('lessons', '0004_word_required_hands'),
    ]

    operations = [
    ]
